global:
  scrape_interval: 60s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'vkipo-app'
    static_configs:
      - targets: ['vkipo-app.railway.internal:3000']
    metrics_path: '/api/metrics'
